apiVersion: v1
kind: ConfigMap
metadata:
  name: internalurls
  labels:
    app: restairline 
data:
  # Internal Services & healthchecks
  restairline: http://restairline
  restairline_hc: http://restairline/api/home/hello
