version: '3.4'

services:

  restairline.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventStoreConnectionString=${EVENT_STORE_DB:-Server=mssql.data;Database=RestAirline;User Id=sa;Password=RestAirline123}
      - ReadModelConnectionString=${READ_MODEL_DB:-Server=mssql.data;Database=RestAirlineRead;User Id=sa;Password=RestAirline123}
    ports:
      - "61200:80"

  mssql.data:
    environment:
    - SA_PASSWORD=RestAirline123
    - ACCEPT_EULA=Y
    ports:
    - "1433:1433"  
      
  mongodb.data:
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  kibana6:
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"

  elasticsearch6:
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
