version: '3.4'

services:

  restairline.api:
    image: restairline:${TAG:-latest}
    build:
      args:
        Version: "1"
      context: ../src
      dockerfile: ./RestAirline.Api/Dockerfile
    depends_on:
      - mssql.data
      - mongodb.data
    container_name: restairline_api

  mssql.data:
    image: microsoft/mssql-server-linux:2017-latest
    
  mongodb.data:
    image: mongo:4.0
    
  kibana6:
    image: docker.elastic.co/kibana/kibana:6.1.4
    depends_on:
      - elasticsearch6

  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
    container_name: elasticsearch

    
    
