version: '3.4'

services:
  restairline.api:
    image: restairline:${TAG:-latest}
    build:
      args:
        Version: "1"
      context: ../
      dockerfile: src/Booking/RestAirline.Booking.Api/Dockerfile
    depends_on:
      - mssql.data
      - mongodb.data
      - elasticsearch
    container_name: restairline_api

  mssql.data:
    image: microsoft/mssql-server-linux:2017-latest
    
  mongodb.data:
    image: mongo:4.0

